spring.application.name=foodly

#zum logging output toggeln:
app.debug.enabled=true

api.key=91aDcNFIoZ278Eqby09w1GJUU26ZJNPdT9bZjvkq

#pfad zur datenbank, momentan im RAM gespeichert und nicht persistent
#COMMENT NEXT LINE TO SWITCH TO FILE
spring.datasource.url=jdbc:h2:mem:testdb

#PERSISTENT / TO SWITCH TO FILE:
#UN-COMMENT THIS    spring.datasource.url=jdbc:h2:file:~/FoodlyDB;AUTO_SERVER=true
#UN-COMMENT THIS    spring.jpa.hibernate.ddl-auto=update

spring.datasource.driverClassName=org.h2.Driver
#sa = system administrator deswegen kein passwort?
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#macht das man unter http://localhost:8080/h2-console datenbank anschauen kann (logindaten von hier)
spring.h2.console.enabled=true