spring.application.name=foodly

#zum logging output toggeln:
app.debug.enabled=falso

api.key=91aDcNFIoZ278Eqby09w1GJUU26ZJNPdT9bZjvkq

#pfad zur datenbank, momentan im RAM gespeichert und nicht persistent
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
#sa = system administrator deswegen kein passwort?
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#macht das man unter http://localhost:8080/h2-console datenbank anschauen kann (logindaten von hier)
spring.h2.console.enabled=true

#spring.jpa.hibernate.ddl-auto=update brauchen wir erst wenn datenbank nicht mehr im memory ist